
language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1

sudo: false

addons:
  code_climate:
    repo_token: fb5f645c9ebea514d16adad90985a73318210543d1531e4e3831e42dffb6ce1f

install:
    - composer install

script: phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml

after_success:
- vendor/bin/test-reporter
